# me
title: ChaoticWeg
email: shawn@chaoticweg.cc
twitter_username: ChaoticWeg
github_username:  ChaoticWeg

# site stuff
description: ye
url: "http://chaoticweg.cc/lorem-ipsum"
baseurl: "/"
repository: "ChaoticWeg/lorem-ipsum"

# build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed